export const LANDING= '/';
export const HOME= '/home';
export const PROFILE= '/profile';
export const MY_WALL= '/mywall/list';
export const MY_WALL_EDIT= '/mywall/edit/:id';
export const OPPORTUNITIES= '/opportunities';
export const ORGANISATIONS= '/organisations';
export const SOCIAL_WALL= '/socialwall';
export const INBOX= '/inbox';
export const FILE_UPLOAD='/fileupload'
export const UPLOAD='/upload'
export const PASSWORD_FORGET = '/pw-forget';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const SIGN_OUT = '/signout';